services:
  - type: web
    name: url-shortener
    runtime: docker
    dockerfilePath: ./Dockerfile
    dockerContext: .
    plan: free
    envVars:
      - key: DB_USERNAME
        value: admin
      - key: DB_PASSWORD
        value: admin
